CREATE DATABASE IF NOT EXISTS practica5;
USE practica5;

CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
name VARCHAR(60) NOT NULL,
surname VARCHAR(70) NOT NULL,
genre ENUM('M', 'F' ,'O') NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
active TINYINT(1) NOT NULL DEFAULT 0,
photo VARCHAR(255) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS actions (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
token VARCHAR(250) NOT NULL UNIQUE,
type ENUM("ACTIVE_ACCOUNT","RESET_PASSWORD","CHANGE_EMAIL") NOT NULL,
new_email VARCHAR(150) NULL,
tiempo_peticion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
tiempo_ejecucion TIMESTAMP NULL,

FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);